services:
  api:
    build: ./src/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    env_file:
      - ./.env
    ports:
      - "7200:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - ${NETWORK_NAME}

  react-frontend:
    build: ./src/frontend/life-sync-react-client
    ports:
      - "4200:8080"
    depends_on:
      - api
    networks:
      - ${NETWORK_NAME}

  angular-frontend:
    build: ./src/frontend/life-sync-angular-client
    ports:
      - "4300:8080"
    depends_on:
      - api
    networks:
      - ${NETWORK_NAME}

  database:
    image: "postgres:17"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - lifesyncdb-data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

networks:
  life-sync-network:
    driver: bridge

volumes:
  lifesyncdb-data:
